### PR TITLE
allow customize html5 validation message

### PR DESCRIPTION
**Pull request by fanjinfei**

### CODE REVIEW

**Comment by wardi** [comment]
This change isn't necessary, you can use the attrs parameter (dict) to add extra attributes instead

**Comment by fanjinfei** [comment]
So I put validationMessge inside attrs dictionary in the caller, and remove this validationMessage from the dictionary in the macro/form.html?

**Comment by wardi** [comment]
yes that's right, I'll close this PR

**Comment by fanjinfei** [comment]
Sorry then ckanext-canada  PR 778 also need to be cancelled.

**Comment by wardi** [comment]
Yes, that's why I said I made a mistake by merging it when I did. I can't revert a single commit because your changes are mixed with other changes, do you mind just fixing it the way it is now with a new PR?

**Comment by fanjinfei** [comment]
ok, I will fix it with a new PR

**Comment by wardi** [comment]
Thanks!

**Pull request closed without merging**
